name: Sync to Gitee
on:
  push:
分支: [ main ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: "https://github.com/wilfredox/water-daily.git"
          destination-repo: "https://Wilfredox:Whx050523@gitee.com/Wilfredox/water-daily.git"
